stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  script:
    # install dependencies
    - npm ci
    # run Cypress tests
    - npm run cy:run:chrome
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/reports
    expire_in: 1 day
